hbase:
 image: tora/hbase
 container_name: prod_hbase
 hostname: hbase_readonly
 ports:
 - "2181:2181"
 - "16000-16100:16000-16100"
 - "8080:8080"
 volumes:
 - ./data/hbase:/opt/hbase-data
 - ./data/conf/:/opt/hbase/conf

tsdb:
 image: tora/tsdb
 container_name: prod_tsdb
 hostname: tsdb_tora
 ports:
 - "4242:4242"
 volumes:
 - ./data/tsdb:/opt/data/tsdb
 links:
 - hbase
